version: '3.1'

services:
  php:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/var/www/html
    links:
      - db
  db:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=php
      - MYSQL_DATABASE=php
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    links:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1